"""One-off training script for the VRS-trajectory anomaly-detection model.

Run via `make train-anomaly-model` (docker compose run --rm risk-service
python -m app.services.anomaly.train) -- NOT run automatically at container
startup or on every build. The resulting model.pkl + metrics.json are
committed to git (see app/ml/README.md); .gitignore explicitly carves this
out from the general "don't commit generated artifacts" rule.

Trains on ~800 synthetic samples (a scoped-down placeholder for the
blueprint's 10,000-sample target -- see README.md/SECURITY.md), generated
from the same VRS weighting formula as vrs_calculator.py so the synthetic
distribution is a reasonable stand-in for real vendor trajectories.
"""

from __future__ import annotations

import json
import random
from pathlib import Path

import joblib
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

from .features import FEATURE_NAMES, TIER_ORDINAL

N_SAMPLES = 800
SEED = 42
MODEL_VERSION = "v1"

ML_DIR = Path(__file__).resolve().parent.parent.parent / "ml"


def _tier_for_vrs(vrs: float) -> str:
    if vrs >= 75:
        return "Critical"
    if vrs >= 55:
        return "High"
    if vrs >= 35:
        return "Medium"
    return "Low"


def _generate_dataset(n_samples: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = random.Random(seed)

    X: list[list[float]] = []
    y: list[int] = []
    for _ in range(n_samples):
        questionnaire_score = rng.uniform(0, 100)
        external_posture_score = rng.uniform(0, 100)
        vulnerability_score = rng.uniform(0, 100)
        breach_history_score = rng.uniform(0, 100)
        threat_intel_score = rng.uniform(0, 100)
        compliance_score = rng.uniform(0, 100)

        # Mirrors vrs_calculator.compute_vrs's weighting exactly.
        weighted_goodness = (
            0.25 * questionnaire_score
            + 0.20 * external_posture_score
            + 0.20 * vulnerability_score
            + 0.15 * breach_history_score
            + 0.15 * threat_intel_score
            + 0.05 * compliance_score
        )
        vrs_score = round(min(100.0, max(0.0, 100.0 - weighted_goodness)), 2)
        tier = _tier_for_vrs(vrs_score)
        vrs_delta_vs_previous = rng.uniform(-30, 30)

        # Anomalous when risk sharply WORSENS (VRS jumps up >15 points) or
        # when both vulnerability exposure and external posture are poor
        # simultaneously (compounding risk, even without a sharp jump).
        label = 1 if (vrs_delta_vs_previous > 15 or (vulnerability_score < 30 and external_posture_score < 40)) else 0
        if rng.random() < 0.05:
            label = 1 - label  # 5% label noise so classes aren't trivially separable

        X.append(
            [
                questionnaire_score,
                external_posture_score,
                vulnerability_score,
                breach_history_score,
                threat_intel_score,
                compliance_score,
                vrs_score,
                float(TIER_ORDINAL[tier]),
                vrs_delta_vs_previous,
            ]
        )
        y.append(label)

    return np.array(X), np.array(y)


def main() -> None:
    X, y = _generate_dataset(N_SAMPLES, SEED)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED, stratify=y)

    model = XGBClassifier(n_estimators=50, max_depth=3, learning_rate=0.1, random_state=SEED, eval_metric="logloss")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    metrics = {
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred, zero_division=0)),
        "recall": float(recall_score(y_test, y_pred, zero_division=0)),
        "f1": float(f1_score(y_test, y_pred, zero_division=0)),
        "roc_auc": float(roc_auc_score(y_test, y_proba)),
        "n_samples": N_SAMPLES,
        "feature_names": FEATURE_NAMES,
        "model_version": MODEL_VERSION,
        "trained_at": "generated by app/services/anomaly/train.py",
    }

    ML_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, ML_DIR / "model.pkl")
    (ML_DIR / "metrics.json").write_text(json.dumps(metrics, indent=2))
    print(f"Trained model saved to {ML_DIR / 'model.pkl'}")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
