"""Regulator-ready report assembly.

Turns a stored assessment + its control results into the report payload:
an attestation-style header, a per-domain framework breakdown, the full
control register, and a prioritised gap list. This is the artefact a
compliance manager hands to an auditor / regulator (CBN, NDPC) to evidence
third-party due diligence.
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..models import ComplianceAssessment, ControlResult
from .assessment_engine import GAP, MET, NOT_APPLICABLE, PARTIAL, CRITICAL_GAP_WEIGHT


def _domain_breakdown_from_rows(rows: list[ControlResult]) -> list[dict]:
    buckets: dict[tuple[str, str], list[ControlResult]] = {}
    for r in rows:
        buckets.setdefault((r.framework, r.domain), []).append(r)

    _credit = {MET: 1.0, PARTIAL: 0.5, GAP: 0.0}
    out: list[dict] = []
    for (framework, domain), rs in buckets.items():
        counts = {MET: 0, PARTIAL: 0, GAP: 0, NOT_APPLICABLE: 0}
        for r in rs:
            counts[r.status] += 1
        applicable = [r for r in rs if r.status != NOT_APPLICABLE]
        if applicable:
            earned = sum(_credit[r.status] * r.weight for r in applicable)
            possible = sum(r.weight for r in applicable)
            score = round(100.0 * earned / possible, 2)
        else:
            score = 100.0
        out.append(
            {
                "framework": framework,
                "domain": domain,
                "total": len(rs),
                "met": counts[MET],
                "partial": counts[PARTIAL],
                "gap": counts[GAP],
                "not_applicable": counts[NOT_APPLICABLE],
                "score": score,
            }
        )
    out.sort(key=lambda x: (x["score"], -x["gap"]))
    return out


def _prioritise_gaps(rows: list[ControlResult]) -> list[ControlResult]:
    gaps = [r for r in rows if r.status in (GAP, PARTIAL)]
    gaps.sort(key=lambda r: (not r.is_critical_gap, r.status != GAP, -r.weight))
    return gaps


def _attestation(assessment: ComplianceAssessment) -> str:
    scope = "the full control library" if assessment.framework == "ALL" else assessment.framework
    return (
        f"This report attests that vendor {assessment.vendor_id} was assessed against "
        f"{scope} on {assessment.created_at:%Y-%m-%d} by {assessment.created_by}. "
        f"Overall weighted compliance score: {float(assessment.compliance_score):.2f}% "
        f"({assessment.status}). {assessment.critical_gap_count} critical gap(s) "
        f"(material controls of weight >= {CRITICAL_GAP_WEIGHT}) require remediation. "
        f"Generated by SC-TPCRS compliance-service; control results are reproducible "
        f"and the audit trail is hash-chained (see audit_log)."
    )


def build_report(assessment: ComplianceAssessment, rows: list[ControlResult]) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc),
        "vendor_id": assessment.vendor_id,
        "framework": assessment.framework,
        "assessment": assessment,
        "framework_breakdown": _domain_breakdown_from_rows(rows),
        "control_register": rows,
        "prioritised_gaps": _prioritise_gaps(rows),
        "attestation": _attestation(assessment),
    }
